from __future__ import annotations

import pandas as pd

from ml.models.vehicle_risk import MODEL_NAME
from ml.registry import ModelRegistryManager
from ml.training import (
    TrainingConfig,
    VehicleRiskTrainer,
)


def vehicle_training_dataframe() -> pd.DataFrame:
    """
    Deterministic development dataset.

    IMPORTANT:
    These labels are generated by the bootstrap-label
    rules in VehicleRiskTrainer. They are suitable for
    validating the MLOps pipeline, not for claiming real
    production model quality.
    """

    return pd.DataFrame(
        {
            "event_count": [
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
            ],
            "avg_speed": [
                50,
                55,
                60,
                65,
                70,
                75,
                80,
                85,
                90,
                95,
            ],
            "max_speed": [
                60,
                65,
                70,
                75,
                80,
                115,
                120,
                125,
                130,
                135,
            ],
            "speed_stddev": [
                2,
                2,
                3,
                3,
                4,
                4,
                5,
                5,
                6,
                6,
            ],
            "avg_rpm": [
                1500,
                1550,
                1600,
                1650,
                1700,
                1750,
                1800,
                1850,
                1900,
                1950,
            ],
            "max_rpm": [
                1800,
                1850,
                1900,
                1950,
                2000,
                2050,
                2100,
                2150,
                2200,
                2250,
            ],
            "avg_fuel_level": [
                80,
                78,
                75,
                72,
                70,
                65,
                60,
                55,
                50,
                45,
            ],
            "min_fuel_level": [
                70,
                68,
                65,
                62,
                60,
                55,
                50,
                45,
                40,
                10,
            ],
            "avg_battery": [
                12.5,
                12.5,
                12.4,
                12.4,
                12.3,
                12.3,
                12.2,
                12.2,
                12.1,
                12.1,
            ],
            "avg_engine_temperature": [
                80,
                81,
                82,
                83,
                84,
                85,
                86,
                87,
                88,
                89,
            ],
            "max_engine_temperature": [
                90,
                91,
                92,
                93,
                94,
                95,
                96,
                97,
                98,
                110,
            ],
        }
    )


def main() -> None:

    dataframe = vehicle_training_dataframe()

    trainer = VehicleRiskTrainer()

    training_result = trainer.train(
        dataframe=dataframe,
        config=TrainingConfig(
            experiment_name=("enterprise-ai-platform"),
            run_name=("vehicle-risk-registry-bootstrap"),
            model_params={
                "n_estimators": 100,
                "random_state": 42,
                "class_weight": "balanced",
            },
            test_size=0.3,
            random_state=42,
        ),
    )

    print("=" * 70)
    print("TRAINING COMPLETE")
    print("=" * 70)
    print("Run ID:", training_result.run_id)
    print(
        "Experiment ID:",
        training_result.experiment_id,
    )
    print(
        "Model URI:",
        training_result.model_uri,
    )
    print(
        "Training samples:",
        training_result.training_samples,
    )
    print(
        "Validation samples:",
        training_result.validation_samples,
    )

    for name, value in training_result.metrics.items():
        print(f"{name}: {value:.6f}")

    metrics = training_result.metrics

    validation_f1 = metrics.get(
        "validation_f1",
        0.0,
    )

    validation_roc_auc = metrics.get(
        "validation_roc_auc",
        0.0,
    )

    evaluation_passed = validation_f1 >= 0.80 and validation_roc_auc >= 0.80

    print()
    print(
        "EVALUATION PASSED:",
        evaluation_passed,
    )

    if not evaluation_passed:
        raise RuntimeError("Model failed evaluation gates; " "registration aborted.")

    registry = ModelRegistryManager()

    registered = registry.register_model(
        model_uri=training_result.model_uri,
        model_name=MODEL_NAME,
        run_id=training_result.run_id,
        evaluation_passed=True,
    )

    print()
    print("=" * 70)
    print("MODEL REGISTERED")
    print("=" * 70)
    print(
        "Model:",
        registered.model_name,
    )
    print(
        "Version:",
        registered.version,
    )
    print(
        "Model URI:",
        registered.model_uri,
    )
    print(
        "Alias:",
        registered.alias,
    )

    registry.promote_to_champion(
        model_name=MODEL_NAME,
        version=registered.version,
    )

    champion = registry.get_champion(MODEL_NAME)

    print()
    print("=" * 70)
    print("MODEL PROMOTED TO CHAMPION")
    print("=" * 70)
    print(
        "Champion model:",
        champion.name,
    )
    print(
        "Champion version:",
        champion.version,
    )
    print(
        "Validation status:",
        champion.tags.get("validation_status"),
    )
    print(
        "Deployment status:",
        champion.tags.get("deployment_status"),
    )


if __name__ == "__main__":
    main()
