from pyspark.sql.types import (
    DoubleType,
    IntegerType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)


bronze_schema = StructType(
    [
        StructField(
            "vehicle_id",
            StringType(),
            True,
        ),
        StructField(
            "event_time",
            TimestampType(),
            True,
        ),
        StructField(
            "latitude",
            DoubleType(),
            True,
        ),
        StructField(
            "longitude",
            DoubleType(),
            True,
        ),
        StructField(
            "speed",
            DoubleType(),
            True,
        ),
        StructField(
            "rpm",
            IntegerType(),
            True,
        ),
        StructField(
            "fuel_level",
            DoubleType(),
            True,
        ),
        StructField(
            "battery",
            DoubleType(),
            True,
        ),
        StructField(
            "engine_temperature",
            DoubleType(),
            True,
        ),
        StructField(
            "gear",
            IntegerType(),
            True,
        ),
    ]
)
