from pyspark.sql.types import (
    DoubleType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

silver_schema = StructType(
    [
        StructField(
            "vehicle_id",
            StringType(),
            True,
        ),
        StructField(
            "event_time",
            TimestampType(),
            True,
        ),
        StructField(
            "latitude",
            DoubleType(),
            True,
        ),
        StructField(
            "longitude",
            DoubleType(),
            True,
        ),
        StructField(
            "speed",
            DoubleType(),
            True,
        ),
        StructField(
            "rpm",
            IntegerType(),
            True,
        ),
        StructField(
            "fuel_level",
            DoubleType(),
            True,
        ),
        StructField(
            "battery",
            DoubleType(),
            True,
        ),
        StructField(
            "engine_temperature",
            DoubleType(),
            True,
        ),
        StructField(
            "gear",
            IntegerType(),
            True,
        ),
        StructField(
            "kafka_key",
            StringType(),
            True,
        ),
        StructField(
            "kafka_topic",
            StringType(),
            True,
        ),
        StructField(
            "kafka_partition",
            IntegerType(),
            True,
        ),
        StructField(
            "kafka_offset",
            LongType(),
            True,
        ),
        StructField(
            "kafka_timestamp",
            TimestampType(),
            True,
        ),
        StructField(
            "raw_value",
            StringType(),
            True,
        ),
        StructField(
            "ingestion_time",
            TimestampType(),
            True,
        ),
        StructField(
            "speed_category",
            StringType(),
            True,
        ),
        StructField(
            "fuel_status",
            StringType(),
            True,
        ),
        StructField(
            "battery_status",
            StringType(),
            True,
        ),
        StructField(
            "vehicle_status",
            StringType(),
            True,
        ),
    ]
)
