"""
Request logging and Prometheus instrumentation middleware.

This middleware is intentionally placed at the outermost application
middleware layer so that it observes responses generated by:

    - FastAPI routes
    - validation handlers
    - authentication middleware
    - 404 responses
    - other 4xx responses
    - 5xx responses
"""

import json
import time

from fastapi import Request
from starlette.middleware.base import BaseHTTPMiddleware

from ai_platform.llm_gateway.logging.logger import get_logger
from ai_platform.llm_gateway.observability.prometheus import (
    ERRORS_TOTAL,
    ESTIMATED_COST_TOTAL,
    HTTP_REQUEST_DURATION_SECONDS,
    HTTP_REQUESTS_TOTAL,
    INPUT_TOKENS_TOTAL,
    MODEL_REQUESTS_TOTAL,
    OUTPUT_TOKENS_TOTAL,
    PROVIDER_REQUESTS_TOTAL,
)
from ai_platform.llm_gateway.security.redaction import (
    sanitize_body,
    sanitize_headers,
)

logger = get_logger()


class RequestLoggingMiddleware(BaseHTTPMiddleware):
    """
    Logs completed HTTP requests and records gateway Prometheus metrics.

    Because this middleware is intended to be outermost, it can observe
    responses generated by inner middleware, including authentication
    responses such as HTTP 401.
    """

    async def dispatch(self, request: Request, call_next):
        logger.info("Request logging middleware executed")

        start = time.perf_counter()

        # ------------------------------------------------------------------
        # Safely inspect request body.
        # ------------------------------------------------------------------

        body = await request.body()

        payload = {}

        if body:
            try:
                parsed_payload = json.loads(body)

                if isinstance(parsed_payload, dict):
                    payload = parsed_payload

            except json.JSONDecodeError:
                payload = {}

        sanitized_payload = sanitize_body(payload)

        provider = payload.get("provider")
        model = payload.get("model")

        # ------------------------------------------------------------------
        # Execute the remainder of the middleware / application stack.
        # ------------------------------------------------------------------

        response = await call_next(request)

        # ------------------------------------------------------------------
        # Request metadata.
        # ------------------------------------------------------------------

        status_code = str(response.status_code)
        method = request.method
        endpoint = request.url.path

        latency_ms = int((time.perf_counter() - start) * 1000)

        client_ip = request.client.host if request.client else "unknown"

        user_agent = request.headers.get(
            "user-agent",
            "unknown",
        )

        headers = dict(request.headers)

        sanitized_headers = sanitize_headers(headers)

        request_id = getattr(
            request.state,
            "request_id",
            None,
        )

        # ------------------------------------------------------------------
        # Usage metrics generated by endpoint handlers.
        # ------------------------------------------------------------------

        metrics = getattr(
            request.state,
            "metrics",
            {},
        )

        tokens_in = metrics.get("tokens_in")
        tokens_out = metrics.get("tokens_out")
        estimated_cost = metrics.get("estimated_cost")

        # ------------------------------------------------------------------
        # Structured request log.
        # ------------------------------------------------------------------

        extra = {
            "request_id": request_id,
            "method": method,
            "endpoint": endpoint,
            "status_code": response.status_code,
            "latency_ms": latency_ms,
            "client_ip": client_ip,
            "user_agent": user_agent,
            "headers": sanitized_headers,
            "request_body": sanitized_payload,
        }

        if provider is not None:
            extra["provider"] = provider

        if model is not None:
            extra["model"] = model

        if tokens_in is not None:
            extra["tokens_in"] = tokens_in

        if tokens_out is not None:
            extra["tokens_out"] = tokens_out

        if estimated_cost is not None:
            extra["estimated_cost"] = estimated_cost

        logger.info(
            "HTTP Request Completed",
            extra=extra,
        )

        # ==================================================================
        # PROMETHEUS
        # ==================================================================

        # ------------------------------------------------------------------
        # HTTP request counter
        # ------------------------------------------------------------------

        HTTP_REQUESTS_TOTAL.labels(
            method=method,
            endpoint=endpoint,
            status_code=status_code,
        ).inc()

        # ------------------------------------------------------------------
        # HTTP request duration histogram
        #
        # IMPORTANT:
        # status_code is included because the canonical histogram declares
        # method, endpoint, status_code as labels.
        # ------------------------------------------------------------------

        HTTP_REQUEST_DURATION_SECONDS.labels(
            method=method,
            endpoint=endpoint,
            status_code=status_code,
        ).observe(latency_ms / 1000.0)

        # ------------------------------------------------------------------
        # Provider metrics
        # ------------------------------------------------------------------

        if provider:
            PROVIDER_REQUESTS_TOTAL.labels(
                provider=provider,
            ).inc()

        # ------------------------------------------------------------------
        # Model metrics
        # ------------------------------------------------------------------

        if model:
            MODEL_REQUESTS_TOTAL.labels(
                model=model,
            ).inc()

        # ------------------------------------------------------------------
        # Token metrics
        # ------------------------------------------------------------------

        if tokens_in is not None:
            INPUT_TOKENS_TOTAL.inc(tokens_in)

        if tokens_out is not None:
            OUTPUT_TOKENS_TOTAL.inc(tokens_out)

        # ------------------------------------------------------------------
        # Estimated cost
        # ------------------------------------------------------------------

        if estimated_cost is not None:
            ESTIMATED_COST_TOTAL.inc(estimated_cost)

        # ------------------------------------------------------------------
        # Error metrics
        #
        # Every HTTP response >= 400 is considered an HTTP gateway error.
        #
        # Therefore:
        #
        #   401 -> llm_gateway_errors_total{status_code="401"}
        #   404 -> llm_gateway_errors_total{status_code="404"}
        #   400 -> llm_gateway_errors_total{status_code="400"}
        #   500 -> llm_gateway_errors_total{status_code="500"}
        #
        # Successful 2xx responses are NOT recorded here.
        # ------------------------------------------------------------------

        if response.status_code >= 400:
            ERRORS_TOTAL.labels(
                status_code=status_code,
            ).inc()

        return response
