pipeline:
  class: gold

reader:
  type: delta
  table: SILVER_TABLE
  path: SILVER_PATH

writer:
  type: delta
  table: GOLD_TABLE
  path: GOLD_PATH
  mode: overwrite
  output_mode: append

transformer:
  type: gold

validator:
  type: noop

metrics:
  type: default

dlq:
  type: noop
