pipeline:
  class: silver

reader:
  type: parquet
  path: BATCH_BRONZE_PATH

writer:
  type: delta
  table: SILVER_TABLE
  path: SILVER_PATH
  checkpoint: SILVER_CHECKPOINT
  mode: append
  output_mode: append

transformer:
  type: silver

validator:
  type: default

metrics:
  type: default

dlq:
  type: default
