"""create usage events

Revision ID: e67f18ee9436
Revises:
Create Date: 2026-09-04 23:44:24.440190

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e67f18ee9436"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=255), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("capability", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usage_events_capability"), "usage_events", ["capability"], unique=False
    )
    op.create_index(op.f("ix_usage_events_event_id"), "usage_events", ["event_id"], unique=True)
    op.create_index(
        op.f("ix_usage_events_request_id"), "usage_events", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_usage_events_status"), "usage_events", ["status"], unique=False)
    op.create_index(op.f("ix_usage_events_timestamp"), "usage_events", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_events_timestamp"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_status"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_request_id"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_event_id"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_capability"), table_name="usage_events")
    op.drop_table("usage_events")
    # ### end Alembic commands ###
