environment: dev

spark:
  master: local[*]

postgres:
  host: localhost
  port: 5432
  database: vehicle_db
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5432/mydb

kafka:
  bootstrap_servers: localhost:9092

storage:
  bronze: bronze/
  silver: silver/
  gold: gold/
